name: goltens_web
description: Goltens (Web) (User/SubAdmin, Admin)
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  goltens_core:
    path: ../goltens_core

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  side_navigation: ^1.0.4
  dio: 4.0.2
  collection: ^1.17.1
  http_parser: ^4.0.2
  intl_phone_field: ^3.1.0
  provider: ^6.0.5
  file_picker: ^5.2.11
  dropdown_textfield: ^1.0.8
  crop_image: ^1.0.6
  printing: ^5.11.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
